### ISSUE TITLE
Permission Error

### ISSUE THREAD

**Issue by samik1994r** [WillReynolds5/AutoGPT-Social#1]
Traceback (most recent call last):
  File "C:\Users\...........\OneDrive\Documents\INSTAGRAM BOT\AutoGPT-Social\instagram_util\convert_jpg.py", line 13, in convert_to_jpg
    os.remove(input_file_path)
PermissionError: [WinError 32] The process cannot access the file because it is being used by another process: 'accounts\\..................................\\queue\\designer_handbag_resting_on_a_marble_surface.jpg'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\...............\OneDrive\Documents\INSTAGRAM BOT\AutoGPT-Social\start_bot.py", line 164, in <module>
    main_job(project_name, post_count)
  File "C:\Users\...................\OneDrive\Documents\INSTAGRAM BOT\AutoGPT-Social\start_bot.py", line 125, in main_job
    prompt, post_content, image_path = start_post(prompt, project_name)
  File "C:\Users\..................\OneDrive\Documents\INSTAGRAM BOT\AutoGPT-Social\start_bot.py", line 38, in start_post
    image_path, description = get_image(project_name)
  File "C:\Users\................\OneDrive\Documents\INSTAGRAM BOT\AutoGPT-Social\start_bot.py", line 54, in get_image
    image_path = convert_to_jpg(os.path.join("accounts", project_name, "queue", image_fn))
  File "C:\Users\................\OneDrive\Documents\INSTAGRAM BOT\AutoGPT-Social\instagram_util\convert_jpg.py", line 17, in convert_to_jpg
    raise IOError(f"Error converting {input_file_path} to JPEG")
OSError: Error converting accounts\...............................\queue\designer_handbag_resting_on_a_marble_surface.jpg to JPEG
PS C:\Users\..............\OneDrive\Documents\INSTAGRAM BOT\AutoGPT-Social>

**Comment by WillReynolds5** [comment]
It looks like the code had trouble converting the image to JPG, which is the required format for instagram. what was the original image format?

**Comment by injaan** [comment]
same error on windows

**Comment by samik1994r** [comment]
Managed to fix it by removing conversion process from the code.. lol xd. (i am not a software developer and barely know coding)
