### ISSUE TITLE
Can't initialize initialize_bot.py <instagram_username> <instagram_password> <openai_api_key>

### ISSUE THREAD

**Issue by chicago666666** [WillReynolds5/AutoGPT-Social#4]
Only the first parameter is accepted and then the script fails 

![image](https://user-images.githubusercontent.com/20189080/235473624-f29a003c-7bee-41a0-b2b7-42e34351a4ca.png)

**Comment by chicago666666** [comment]
(AutoGPT-Social) M:\ASH\InstagramGPT\AutoGPT-Social>python start_bot.py oldman.freeman2023 2
Posting - oldman.freeman2023
Traceback (most recent call last):
  File "M:\ASH\InstagramGPT\AutoGPT-Social\instagram_util\convert_jpg.py", line 14, in convert_to_jpg
    os.remove(input_file_path)
PermissionError: [WinError 32] Процесс не может получить доступ к файлу, так как этот файл занят другим процессом: 'accounts\\oldman.freeman2023\\queue\
\digital_gold.jpg'

During handling of the above exception, another exception occurred:
  File "M:\ASH\InstagramGPT\AutoGPT-Social\start_bot.py", line 54, in get_image
    image_path = convert_to_jpg(os.path.join("accounts", project_name, "queue", image_fn))
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "M:\ASH\InstagramGPT\AutoGPT-Social\instagram_util\convert_jpg.py", line 18, in convert_to_jpg
    raise IOError(f"Error converting {input_file_path} to JPEG")
OSError: Error converting accounts\oldman.freeman2023\queue\digital_gold.jpg to JPEG

Always new errors.... It totally does not work for me =(

Can you record video how you use your own program!?!

**Comment by WillReynolds5** [comment]
the code is failing to convert your image to JPG, which could be happening for a number of reasons. If your images are pre-converted to JPG and not corrupted, do this.

in start_bot.py, edit line 54 from
image_path = convert_to_jpg(os.path.join("accounts", project_name, "queue", image_fn))
to 
image_path = os.path.join("accounts", project_name, "queue", image_fn)

that should fix your problem
